# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.3.0
        hooks:
            -   id: trailing-whitespace
            -   id: end-of-file-fixer
            -   id: check-yaml
            -   id: no-commit-to-branch
                args: [--branch, staging, --branch, main]
            -   id: requirements-txt-fixer
    -   repo: https://github.com/psf/black
        rev: 22.6.0
        hooks:
            -   id: black
    -   repo: https://github.com/pycqa/isort
        rev: 5.10.1
        hooks:
            -   id: isort
                name: isort (python)
    -   repo: https://github.com/FelixSeptem/pre-commit-golang.git
        rev: "12f5442f51377b10b26651ad745206bbe1500ad6"
        hooks:
            -   id: bazel-buildifier
